language: python

python:
  - "2.7"
  - "2.6"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse unittest2; fi
    - pip install -r requirements.txt --use-mirrors

script:  python setup.py test
